Make Travis test with GHC 7.10

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,40 @@
-sudo: false
+# Based on: https://github.com/hvr/multi-ghc-travis
 
 cache:
   directories:
     - .cabal-sandbox
 
-language: haskell
-
-ghc:
-  - 7.8
-  - 7.6
-  - 7.4
+env:
+ - CABALVER=1.18 GHCVER=7.6.3
+ - CABALVER=1.18 GHCVER=7.8.3
+ - CABALVER=1.22 GHCVER=7.10.1
 
 before_install:
-  - cabal install alex happy
-  - cabal sandbox init
-  - cabal sandbox hc-pkg dump
-  - cabal install --only-dep --enable-tests -v2 --dry-run
-  - cabal install --only-dep --enable-tests
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - travis_retry cabal update
+ - export PATH=$HOME/.cabal/bin:$PATH
+ - cabal install happy alex
 
+install:
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - cabal sandbox init
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
+
+script:
+ - cabal configure --enable-tests --enable-benchmarks -v2
+ - cabal build
+ - cabal test
+ - cabal check
+ - cabal sdist
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
