indentation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -35,22 +35,22 @@ install:
   - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls
 
 script:
- - cabal configure --enable-tests --enable-benchmarks -v2
- - cabal build
- - cabal test
- - cabal check
- - cabal sdist
- - export SRC_TGZ=$(cabal info . | awk '{print $2;exit}');
-   cd dist/;
-   if [ -f "$SRC_TGZ".tar.gz ]; then
-     cabal unpack "$SRC_TGZ".tar.gz;
-     cd "$SRC_TGZ";
-     cabal sandbox init --sandbox ../../.cabal-sandbox;
-     cabal configure --disable-optimization --enable-test;
-     cabal build;
-     cabal install --disable-optimization --force-reinstalls;
-   else
-      echo "expected '$SRC_TGZ.tar.gz' not found";
-      exit 1;
-   fi
+  - cabal configure --enable-tests --enable-benchmarks -v2
+  - cabal build
+  - cabal test
+  - cabal check
+  - cabal sdist
+  - export SRC_TGZ=$(cabal info . | awk '{print $2;exit}');
+    cd dist/;
+    if [ -f "$SRC_TGZ".tar.gz ]; then
+      cabal unpack "$SRC_TGZ".tar.gz;
+      cd "$SRC_TGZ";
+      cabal sandbox init --sandbox ../../.cabal-sandbox;
+      cabal configure --disable-optimization --enable-test;
+      cabal build;
+      cabal install --disable-optimization --force-reinstalls;
+    else
+       echo "expected '$SRC_TGZ.tar.gz' not found";
+       exit 1;
+    fi
 
